
#endpoints: # deprecated since spring-boot 2.x
#  env.sensitive: ${ENDPOINTS_ENV_SENSITIVE:true}
#  health.sensitive: ${ENDPOINTS_HEALTH_SENSITIVE:false}

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://user:user_pass@eureka-standalone:8761/eureka/}
  instance:
    health-check-url: http://${SIDECAR_HOSTNAME:${SIDECAR_IPADDRESS:${spring.cloud.client.ip-address:${spring.cloud.client.hostname:localhost}}}}:${SIDECAR_PORT:8761}${SIDECAR_HEALTHURI:/health}
    home-page-url: http://${SIDECAR_HOSTNAME:${SIDECAR_IPADDRESS:${spring.cloud.client.ip-address:${spring.cloud.client.hostname:localhost}}}}:${SIDECAR_PORT:8761}${SIDECAR_HOMEPAGEURI:/}
    instance-id: ${spring.application.name}:${SIDECAR_HOSTNAME:${SIDECAR_IPADDRESS:${spring.cloud.client.ip-address:${spring.cloud.client.hostname:${random.int}}}}}:${SERVER_PORT:5678}
    prefer-ip-address: ${EUREKA_INSTANCE_PREFERIPADDRESS:true}
    status-page-url: http://${SIDECAR_HOSTNAME:${SIDECAR_IPADDRESS:${spring.cloud.client.ip-address:${spring.cloud.client.hostname:localhost}}}}:${SIDECAR_PORT:8761}/info

logging:
  #file: ${LOG_FILE:${CONTAINER_HOST_NAME:${spring.cloud.client.hostname:${spring.application.name}-${server.port}}}}.log
  #path: ${LOG_PATH:${user.dir}/data/logs/${spring.application.name}}
  level:
    jndi: ${LOGGING_LEVEL_ROOT:INFO}
    org.springframework.boot.actuate.endpoint.jmx.EndpointMBeanExporter: ${ENDPOINT_LOGGING_LEVEL_ROOT:WARN}
    org.springframework.boot.actuate.endpoint.mvc.EndpointHandlerMapping: ${ENDPOINT_LOGGING_LEVEL_ROOT:WARN}
    org.springframework.boot.web.servlet.FilterRegistrationBean: ${ENDPOINT_LOGGING_LEVEL_ROOT:WARN}
    org.springframework.boot.web.servlet.ServletRegistrationBean: ${ENDPOINT_LOGGING_LEVEL_ROOT:WARN}
    org.springframework.core.type.classreading.AnnotationAttributesReadingVisitor: INFO
    org.springframework.jmx.export.annotation.AnnotationMBeanExporter: ${ENDPOINT_LOGGING_LEVEL_ROOT:WARN}
    org.springframework.jndi: ${LOGGING_LEVEL_ROOT:INFO}
    org.springframework.web.servlet.handler.SimpleUrlHandlerMapping: ${ENDPOINT_LOGGING_LEVEL_ROOT:WARN}
    org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerMapping: ${ENDPOINT_LOGGING_LEVEL_ROOT:WARN}
    root: ${LOGGING_LEVEL_ROOT:DEBUG}

management:
  endpoint:
    shutdown.enabled: ${MANAGEMENT_ENDPOINT_SHUTDOWN_ENABLED:true}
    health:
      show-details: ${MANAGEMENT_ENDPOINT_HEALTH_SHOWDETAILS:ALWAYS}
      roles: ${MANAGEMENT_ENDPOINT_HEALTH_ROLES:ACTUATOR}
  endpoints:
    web: # since spring-boot 2.x
      #base-path: ${MANAGEMENT_ENDPOINTS_WEB_BASEPATH:} # default: /actuator, do not set this value on sidecar (management.context-path deprecated since spring-boot 2.x)
      exposure:
        include: "${MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE:*}"
        exclude: "${MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_EXCLUDE:}"
#  security: # deprecated since spring-boot 2.x
#    enabled: true
#    roles: SUPERUSER
#    sessions: stateless

server:
  #servlet.context-path: # do not set server.servlet.context-path on sidecar (server.context-path deprecated since spring-boot 2.x)
  port: ${SERVER_PORT:5678}

sidecar:
  health-uri: http://${SIDECAR_HOSTNAME:${SIDECAR_IPADDRESS:${spring.cloud.client.ip-address:${spring.cloud.client.hostname:localhost}}}}:${SIDECAR_PORT:8761}${SIDECAR_HEALTHURI:/health} # mandatory
  home-page-uri: http://${SIDECAR_HOSTNAME:${SIDECAR_IPADDRESS:${spring.cloud.client.ip-address:${spring.cloud.client.hostname:localhost}}}}:${SIDECAR_PORT:8761}${SIDECAR_HOMEPAGEURI:/} # optional
  hostname: ${SIDECAR_HOSTNAME:${SIDECAR_IPADDRESS:${spring.cloud.client.ip-address:${spring.cloud.client.hostname:}}}} # optional
  ip-address: ${SIDECAR_IPADDRESS:${spring.cloud.client.ip-address:}} # optional
  # sidecar.port is the port on which the non-JVM application listens
  port: ${SIDECAR_PORT:8761} # mandatory

spring:
  application.name: ${SPRING_APPLICATION_NAME:the-name-of-non-JVM-application-or-service}
  cloud:
    inetutils:
      preferred-networks: ${SPRING_CLOUD_INETUTILS_IGNOREDINTERFACES:^192\.168\..+, ^172\.30\..+, ^10\..+}
      ignored-interfaces: ${SPRING_CLOUD_INETUTILS_IGNOREDINTERFACES:^[a-z]?tun[0-9]*, ^awdl[0-9]*, ^lo[0-9]*}

  security:
    enabled: false
    user:
      name: admin
      password: ${SPRING_SECURITY_USER_PASSWORD:${random.uuid}}
      roles: ${SPRING_SECURITY_USER_ROLES:ACTUATOR, ADMIN, SUPERUSER, USER}
